version: "3.9"

services:
  frontend:
    build: ../frontend       
    container_name: blog-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:5000
    depends_on:
      - backend

  backend:
    build: ../backend         
    container_name: blog-backend
    ports:
      - "5000:5000"
    environment:
      PGUSER: postgres
      PGPASSWORD: 12345
      PGDATABASE: blogdb
      PGHOST: db
      PGPORT: 5432
      HF_TOKEN: ${HF_TOKEN}
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: blog-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: blogdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
